name: SDK publish

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
 
jobs:
  checks:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
          fetch-depth: 2

  set-tag:
    needs: [checks]
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.extract_version.outputs.sdk_version }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
      - name: Extract SDK version
        id: extract_version
        run: |
          SDK_VERSION=$(grep '^SDK_VERSION_NAME=' gradle.properties | cut -d '=' -f2)
          echo "Extracted SDK version: ${SDK_VERSION}"
          echo "sdk_version=${SDK_VERSION}" >> $GITHUB_OUTPUT
          echo "SDK_VERSION=${SDK_VERSION}" >> $GITHUB_ENV
      - name: Create tag
        run: |
          git tag "${{ env.SDK_VERSION }}"
          git push origin "${{ env.SDK_VERSION }}"

  release-github:
    needs: [set-tag]
    runs-on: macos-latest
    outputs:
      tag: ${{ needs.set-tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
      - name: Build XCFramework
        run: ./make-ios-framework.sh
      - name: Github Release generation
        run: ./.github/git-release-ci.sh
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Verify framework existence
        run: ls -R mindbox-common/build/XCFrameworks/release
      - name: Upload XCFramework to release
        run: |
          gh release upload ${{ needs.set-tag.outputs.tag }} \
          mindbox-common/build/XCFrameworks/release/MindboxCommon.xcframework.zip \
          --clobber
        env:
          GH_TOKEN: ${{ github.token }}

  trigger-repo-b:
    needs: [release-github]
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow in repo B
        run: |
          echo "Triggering workflow in repo B..."
          echo "TAG=${{ needs.release-github.outputs.tag }}"
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
            https://api.github.com/repos/vailence/TempLoggerRepo/dispatches \
            -d "{\"event_type\": \"download_xcframework\", \"client_payload\": {\"version\": \"${{ needs.release-github.outputs.tag }}\"}}"
